databases:
  - name: disfood_DB
    databaseName: disfood_db
    user: disfood
    region: singapore

services:
  - type: web
    name: disfood
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: disfood_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

